"""categoria_fk_en_transaccion

Revision ID: ac7448e0d2ca
Revises: e4de7ae787fd
Create Date: 2026-06-12 16:32:44.553103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac7448e0d2ca'
down_revision: Union[str, Sequence[str], None] = 'e4de7ae787fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categorias', sa.Column('usuario_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'categorias', 'usuarios', ['usuario_id'], ['id'])
    op.alter_column('transacciones', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transacciones', 'usuario_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'categorias', type_='foreignkey')
    op.drop_column('categorias', 'usuario_id')
    # ### end Alembic commands ###
